name: Tag Version

on:
  push:
    branches: [ develop ]

jobs:
  tag-release:
    runs-on: ubuntu-latest
    env:
      VERSION_FILE: ProjectSettings/ProjectSettings.asset
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
      
      - name: Assign version string
        run: |
          NEW_VERSION=`grep -Po "bundleVersion: \K[0-9.]*" ${{ env.VERSION_FILE }}`
          echo '::set-output name=VERSION::'v$NEW_VERSION
        id: branch

      - name: Tag latest version
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.branch.outputs.VERSION }}
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
