name: Upload Build

on:
  pull_request:
    branches: [ master ]

jobs:
  upload-build:
    runs-on: ubuntu-latest
    env:
      VERSION_FILE: Assets/Resources/VERSION.txt
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Setup cache for the Unity build
        uses: actions/cache@v2
        with:
          path: Library
          key: ozymandias-unity-linux
          restore-keys: |
            ozymandias-unity-linux

      - name: Setup cache for the steamcmd build
        uses: actions/cache@v2
        with:
          path: steampipe/ContentBuilder/content/linux_content
          key: ozymandias-steampipe-linux
          restore-keys: |
            ozymandias-steampipe-linux

      - name: Get current version string
        run: |
          VERSION=`cat ${{ env.VERSION_FILE }}`
          echo '::set-output name=VERSION::'$VERSION
        id: version

      - name: Run Unity build
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENCE }}
        with:
          targetPlatform: StandaloneLinux64
          version: ${{ steps.version.outputs.VERSION }}
      
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
        
      - name: Move build files to steampipe content folder
        run: |
          mv build/* steampipe/ContentBuilder/content/linux_content

      - name: Run steamcmd login, update, build and upload
        run: |
          chmod +x steampipe/ContentBuilder/builder_osx/steamcmd
      #     steampipe/ContentBuilder/builder_osx/steamcmd.sh +login ${{ secrets.STEAMWORKS_USERNAME }} ${{ secrets.STEAMWORKS_PASSWORD }} +run_app_build ../scripts/app_build_1524530.vdf +quit
  # windows:
  # linux:
