name: Validate Version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-bumped:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download semver script
        run: |
          curl https://raw.githubusercontent.com/Ariel-Rodriguez/sh-semversion-2/main/semver2.sh -o semver2.sh
          chmod 755 ./semver2.sh
      
      - name: Compare semvers
        run: |
          NEW_VERSION=`cat Assets/Resources/VERSION.txt`
          echo "$NEW_VERSION"
          ./semver2.sh "$NEW_VERSION" v1.0.0 | { read -r var; if [ "$var" -gt 0 ]; then exit 0; else exit 1; fi; }

#   tag-release:
#     runs-on: ubuntu-latest
