name: Validate Version

on:
  pull_request:
    branches: [ develop ]

jobs:
  check-bumped:
    runs-on: ubuntu-latest
    env:
      VERSION_FILE: ProjectSettings/ProjectSettings.asset
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        
      - name: Assign new version string
        run: |
          NEW_VERSION=`grep -Po "bundleVersion: \K[0-9.]*" ${{ env.VERSION_FILE }}`
          echo '::set-output name=VERSION::'v$NEW_VERSION
        id: branch
      
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
      
      - name: Assign old version string
        run: |
          OLD_VERSION=`grep -Po "bundleVersion: \K[0-9.]*" ${{ env.VERSION_FILE }}`
          echo '::set-output name=VERSION::'v$OLD_VERSION
        id: develop

      - name: Download semver script
        run: |
          curl https://raw.githubusercontent.com/Ariel-Rodriguez/sh-semversion-2/main/semver2.sh -o semver2.sh
          chmod 755 ./semver2.sh
      
      - name: Compare semvers
        run: |
          NEW_VERSION=`echo ${{ steps.branch.outputs.VERSION }}`
          OLD_VERSION=`echo ${{ steps.develop.outputs.VERSION }}`
          ./semver2.sh $NEW_VERSION $OLD_VERSION | { read -r var; if [ "$var" -gt 0 ]; then exit 0; else echo "AntiquatedVersionError: upstream version ("$NEW_VERSION") is <= develop branch version ("$OLD_VERSION"). Please update VERSION.txt to newer semantic version before merging." && exit 1; fi; }
