name: Validate Version

on:
  pull_request:
    branches: [ master ]

jobs:
  check-bumped:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        
      - name: Assign new version string
        run: NEW_VERSION=`cat Assets/Resources/VERSION.txt`
      
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
      
      - name: Assign old version string
        run: OLD_VERSION=`cat Assets/Resources/VERSION.txt`

      - name: Download semver script
        run: |
          curl https://raw.githubusercontent.com/Ariel-Rodriguez/sh-semversion-2/main/semver2.sh -o semver2.sh
          chmod 755 ./semver2.sh
      
      - name: Compare semvers
        run: |
          NEW_VERSION=`cat Assets/Resources/VERSION.txt`
          ./semver2.sh "$NEW_VERSION" "$OLD_VERSION" | { read -r var; if [ "$var" -gt 0 ]; then exit 0; else exit 1; fi; }
